require("core.keymaps-conf")
require("core.options-conf")
require("core.plugins-reg-conf")
require("config.mason")
require("config.blink")
require("config.treesiter")
require("config.colorscheme")
require("config.lsp")
require("config.conform")
require("config.telescope")

require("nvim-autopairs").setup()
require("telescope").setup()
require("ibl").setup()
require("luasnip.loaders.from_vscode").lazy_load()
require("transparent").setup({})
require("staline").setup()
