vim.pack.add({
    { src = "https://github.com/rafamadriz/friendly-snippets",              version = vim.version.range('*'), },
    { src = "https://github.com/L3MON4D3/LuaSnip",                          version = vim.version.range('*'), },
    { src = "https://github.com/Saghen/blink.cmp",                          version = vim.version.range('*'), },
    { src = "https://github.com/windwp/nvim-autopairs", },
    { src = "https://github.com/neovim/nvim-lspconfig", },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter" },
    { src = "https://github.com/mason-org/mason-lspconfig.nvim", },
    { src = "https://github.com/mason-org/mason.nvim" },
    { src = "https://github.com/nvim-lua/plenary.nvim" },
    { src = "https://github.com/nvim-telescope/telescope.nvim" },
    { src = "https://github.com/nvim-tree/nvim-web-devicons" },
    { src = "https://github.com/lukas-reineke/indent-blankline.nvim" },
    { src = "https://github.com/rebelot/kanagawa.nvim", },
    { src = "https://github.com/nvim-telescope/telescope-file-browser.nvim" },
    { src = "https://github.com/stevearc/conform.nvim" },
})
