{ pkgs, apple-fonts, ... }:
{
  home.packages = with pkgs; [
    wlogout
    cachix
    unzip
    apple-cursor
    swaybg
    waybar
    fuzzel
    btop
    rofi
    apple-fonts.sf-pro
    feh
    picom
    fastfetch
    lsd
    stylua
    nixfmt
    prettierd
    nixd
    rustfmt
    lua-language-server
    bash-language-server
    rust-analyzer
    vscode-langservers-extracted # HTML, CSS, JSON, ESLint
    typescript-language-server
    tailwindcss-language-server
    svelte-language-server
    emmet-ls
    eslint_d
    clang-tools
    nodejs
    python3
    lsd
    tree
    tmux
    cargo
    rustc
    clang
    fzf
    gnumake
    xclip
    dconf
    vscode-fhs
    libnotify
  ];
}
